[package]
name = "jsdotlua/timers"
version = "1.2.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
collections = "jsdotlua/collections@1.2.6"
