[package]
name = "jsdotlua/luau-polyfill"
version = "1.2.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
boolean = "jsdotlua/boolean@1.2.6"
collections = "jsdotlua/collections@1.2.6"
console = "jsdotlua/console@1.2.6"
"es7-types" = "jsdotlua/es7-types@1.2.6"
"instance-of" = "jsdotlua/instance-of@1.2.6"
math = "jsdotlua/math@1.2.6"
number = "jsdotlua/number@1.2.6"
string = "jsdotlua/string@1.2.6"
timers = "jsdotlua/timers@1.2.6"
"symbol-luau" = "jsdotlua/symbol-luau@^1.0.0"
